name: Trigger auto deployment for artifact-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/artifact-app-AutoDeployTrigger-47854ba7-cd1b-4b70-a875-be2031e6ffa8.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ARTIFACTAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ARTIFACTAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ARTIFACTAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: ca07fce56c64acr.azurecr.io
          registryUsername: ${{ secrets.ARTIFACTAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ARTIFACTAPP_REGISTRY_PASSWORD }}
          containerAppName: artifact-app
          resourceGroup: artifact-rg
          imageToBuild: ca07fce56c64acr.azurecr.io/artifact-app:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


