name: Trigger auto deployment for cntd

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/cntd-AutoDeployTrigger-ddae64e5-5f89-4dc6-af95-449d2e4244db.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CNTD_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CNTD_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CNTD_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: testerregistry.azurecr.io
          registryUsername: ${{ secrets.CNTD_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CNTD_REGISTRY_PASSWORD }}
          containerAppName: cntd
          resourceGroup: ogfstage246-2210-gayathri
          imageToBuild: testerregistry.azurecr.io/cntd:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


