name: Trigger auto deployment for continuous-deployment-app1

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/continuous-deployment-app1-AutoDeployTrigger-41f1779b-c375-4b4a-8d1c-7ef0b2e4ea5a.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTINUOUSDEPLOYMENTAPP1_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTINUOUSDEPLOYMENTAPP1_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTINUOUSDEPLOYMENTAPP1_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: stewsregistry.azurecr.io
          registryUsername: ${{ secrets.CONTINUOUSDEPLOYMENTAPP1_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTINUOUSDEPLOYMENTAPP1_REGISTRY_PASSWORD }}
          containerAppName: continuous-deployment-app1
          resourceGroup: continuousDeployment
          imageToBuild: stewsregistry.azurecr.io/continuous-deployment-app1:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


