name: Trigger auto deployment for cont-service

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/cont-service-AutoDeployTrigger-8509ab8b-1c3f-4f32-8b57-195e4271aacf.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CONTSERVICE_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: antuxtest.azurecr.io
          registryUsername: ${{ secrets.CONTSERVICE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTSERVICE_REGISTRY_PASSWORD }}
          containerAppName: cont-service
          resourceGroup: OGFs220-0708-gayathri
          imageToBuild: antuxtest.azurecr.io/cont-azure:${{ github.sha }}
          dockerfilePath: Dockerfile

     

