name: Trigger auto deployment for containerapp-euap

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/containerapp-euap-AutoDeployTrigger-61a1ebf2-3263-4f97-95c6-47288bacb542.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: stpelleg002.azurecr.io
          username: ${{ secrets.CONTAINERAPPEUAP_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINERAPPEUAP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: stpelleg002.azurecr.io/containerapp-euap:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CONTAINERAPPEUAP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n containerapp-euap -g containerapps-rg --server stpelleg002.azurecr.io --username  ${{ secrets.CONTAINERAPPEUAP_REGISTRY_USERNAME }} --password ${{ secrets.CONTAINERAPPEUAP_REGISTRY_PASSWORD }}
            az containerapp update -n containerapp-euap -g containerapps-rg --image stpelleg002.azurecr.io/containerapp-euap:${{ github.sha }}
