name: Trigger auto deployment for final-oidc-app3

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/final-oidc-app3-AutoDeployTrigger-1873e613-f583-465e-a7c1-f125829e62f8.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.FINALOIDCAPP3_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FINALOIDCAPP3_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FINALOIDCAPP3_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: finaloidcregistry.azurecr.io
          registryUsername: ${{ secrets.FINALOIDCAPP3_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FINALOIDCAPP3_REGISTRY_PASSWORD }}
          containerAppName: final-oidc-app3
          resourceGroup: final-oidc-rg
          imageToBuild: finaloidcregistry.azurecr.io/final-oidc-app3:${{ github.sha }}
          


