name: Trigger auto deployment for identity-location-test-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/identity-location-test-app-AutoDeployTrigger-ef967dff-bfe0-44a7-8dc9-3f926d0219df.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.IDENTITYLOCATIONTESTAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.IDENTITYLOCATIONTESTAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.IDENTITYLOCATIONTESTAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: ca07fce56c64acr.azurecr.io
          registryUsername: ${{ secrets.IDENTITYLOCATIONTESTAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.IDENTITYLOCATIONTESTAPP_REGISTRY_PASSWORD }}
          containerAppName: identity-location-test-app
          resourceGroup: identity-location-test-rg
          imageToBuild: ca07fce56c64acr.azurecr.io/identity-location-test-app:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


