name: Trigger auto deployment for myapp2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/myapp2-AutoDeployTrigger-b6804960-9014-485c-bef2-c4d9759c9f9d.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: stpelleg09.azurecr.io
          username: ${{ secrets.MYAPP2_REGISTRY_USERNAME }}
          password: ${{ secrets.MYAPP2_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: stpelleg09.azurecr.io/myapp2:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MYAPP2_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n myapp2 -g containerapps-rg --server stpelleg09.azurecr.io --username  ${{ secrets.MYAPP2_REGISTRY_USERNAME }} --password ${{ secrets.MYAPP2_REGISTRY_PASSWORD }}
            az containerapp update -n myapp2 -g containerapps-rg --image stpelleg09.azurecr.io/myapp2:${{ github.sha }}
